title: "–†–µ–º–æ–Ω—Ç —Å–º–∞—Ä—Ç—Ñ–æ–Ω–æ–≤ –∏ –Ω–æ—É—Ç–±—É–∫–æ–≤"
description: "–≥. –î—Ä–æ–≥–∏—á–∏–Ω, —É–ª. –õ–µ–Ω–∏–Ω–∞ 141–∞ | <a href='tel:+375297256982'>üìû +375 (29) 725-69-82</a><br>–°–ª–æ–∂–Ω—ã–µ —Ä–∞–∑–±–ª–æ–∫–∏—Ä–æ–≤–∫–∏, –≤–æ—Å—Å—Ç–∞–Ω–æ–≤–ª–µ–Ω–∏–µ –ø–æ—Å–ª–µ –≤–æ–¥—ã, –ø—Ä–æ—à–∏–≤–∫–∞."

theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag

url: "https://alexdrog.github.io"
baseurl: ""
show_downloads: false
