remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Ремонт техники | Дрогичин"
description: "Профессиональный ремонт компьютеров, ноутбуков и смартфонов. Прошивка, разблокировка, обновление навигаторов. Выезд и диагностика."

contact:
  phone: "+375 (29) 725-69-82"
  telegram: "https://t.me/AlexDrog81"
  
  
defaults:
  - scope:
      path: ""
    values:
      layout: default
